# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://daiacassol.github.io/
title: Daiane Cassol
email: cassol.daia@gmail.com
author: Daiane Cassol
description: "Daiane's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/daiacassol  
  - icon: envelope-o
    title: email
    url: mailto:cassol.daia@gmail.com
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/daiane-cassol-76983168/
  - icon: file-pdf-o
    title: CV
    url: img/CV_CASSOL.pdf
  - icon: website
    title: CV Lattes
    url: http://lattes.cnpq.br/4004940058931557
#  - icon: twitter
#    title: twitter
#    url: https://twitter.com/danicassol

